version: "3.8"
services:
  db:
    image: postgres:15.3-bullseye
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - app-db-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app-network

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    # command: bash -c "/usr/bin/psql postgresql://postgres:development@db:5432 -c 'drop database if exists tweets' && /usr/bin/psql postgresql://postgres:development@db:5432 -c 'create database tweets' && ./app/tweets"
    # command: bash -c "/usr/bin/psql postgresql://postgres:development@db:5432 -c 'drop database if exists tweets' && /usr/bin/psql postgresql://postgres:development@db:5432 -c 'create database tweets'"
    command: >
      bash -c "/usr/bin/psql postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}
      -c 'drop database if exists ${DB_NAME}' && /usr/bin/psql
      postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT} -c 'create database ${DB_NAME}'"
    networks:
      - app-network

volumes:
  app-db-data:


networks:
  app-network:
