// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: protobuf/tweets_service/tweets_service.proto

package tweets_service

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tweet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text      string               `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UserId    string               `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RepliesTo string               `protobuf:"bytes,4,opt,name=replies_to,json=repliesTo,proto3" json:"replies_to,omitempty"`
	QuoteTo   string               `protobuf:"bytes,5,opt,name=quote_to,json=quoteTo,proto3" json:"quote_to,omitempty"`
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Tweet) Reset() {
	*x = Tweet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tweet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tweet) ProtoMessage() {}

func (x *Tweet) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tweet.ProtoReflect.Descriptor instead.
func (*Tweet) Descriptor() ([]byte, []int) {
	return file_protobuf_tweets_service_tweets_service_proto_rawDescGZIP(), []int{0}
}

func (x *Tweet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tweet) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Tweet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Tweet) GetRepliesTo() string {
	if x != nil {
		return x.RepliesTo
	}
	return ""
}

func (x *Tweet) GetQuoteTo() string {
	if x != nil {
		return x.QuoteTo
	}
	return ""
}

func (x *Tweet) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PostTweetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text      string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UserId    string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RepliesTo string `protobuf:"bytes,4,opt,name=replies_to,json=repliesTo,proto3" json:"replies_to,omitempty"`
	QuoteTo   string `protobuf:"bytes,5,opt,name=quote_to,json=quoteTo,proto3" json:"quote_to,omitempty"`
}

func (x *PostTweetRequest) Reset() {
	*x = PostTweetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTweetRequest) ProtoMessage() {}

func (x *PostTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTweetRequest.ProtoReflect.Descriptor instead.
func (*PostTweetRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_tweets_service_tweets_service_proto_rawDescGZIP(), []int{1}
}

func (x *PostTweetRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PostTweetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostTweetRequest) GetRepliesTo() string {
	if x != nil {
		return x.RepliesTo
	}
	return ""
}

func (x *PostTweetRequest) GetQuoteTo() string {
	if x != nil {
		return x.QuoteTo
	}
	return ""
}

type PostTweetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tweet *Tweet `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
}

func (x *PostTweetResponse) Reset() {
	*x = PostTweetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTweetResponse) ProtoMessage() {}

func (x *PostTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTweetResponse.ProtoReflect.Descriptor instead.
func (*PostTweetResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_tweets_service_tweets_service_proto_rawDescGZIP(), []int{2}
}

func (x *PostTweetResponse) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

type DeleteTweetByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TweetId string `protobuf:"bytes,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
}

func (x *DeleteTweetByIdRequest) Reset() {
	*x = DeleteTweetByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTweetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTweetByIdRequest) ProtoMessage() {}

func (x *DeleteTweetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTweetByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteTweetByIdRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_tweets_service_tweets_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTweetByIdRequest) GetTweetId() string {
	if x != nil {
		return x.TweetId
	}
	return ""
}

type DeleteTweetByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTweetByIdResponse) Reset() {
	*x = DeleteTweetByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTweetByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTweetByIdResponse) ProtoMessage() {}

func (x *DeleteTweetByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTweetByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteTweetByIdResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_tweets_service_tweets_service_proto_rawDescGZIP(), []int{4}
}

type GetTweetByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TweetId string `protobuf:"bytes,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
}

func (x *GetTweetByIdRequest) Reset() {
	*x = GetTweetByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTweetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetByIdRequest) ProtoMessage() {}

func (x *GetTweetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTweetByIdRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_tweets_service_tweets_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTweetByIdRequest) GetTweetId() string {
	if x != nil {
		return x.TweetId
	}
	return ""
}

type GetTweetByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tweet *Tweet `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
}

func (x *GetTweetByIdResponse) Reset() {
	*x = GetTweetByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTweetByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetByIdResponse) ProtoMessage() {}

func (x *GetTweetByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetByIdResponse.ProtoReflect.Descriptor instead.
func (*GetTweetByIdResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_tweets_service_tweets_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetTweetByIdResponse) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

type GetAllTweetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllTweetsRequest) Reset() {
	*x = GetAllTweetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllTweetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTweetsRequest) ProtoMessage() {}

func (x *GetAllTweetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTweetsRequest.ProtoReflect.Descriptor instead.
func (*GetAllTweetsRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_tweets_service_tweets_service_proto_rawDescGZIP(), []int{7}
}

type GetAllTweetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tweets []*Tweet `protobuf:"bytes,1,rep,name=tweets,proto3" json:"tweets,omitempty"`
}

func (x *GetAllTweetsResponse) Reset() {
	*x = GetAllTweetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllTweetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTweetsResponse) ProtoMessage() {}

func (x *GetAllTweetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTweetsResponse.ProtoReflect.Descriptor instead.
func (*GetAllTweetsResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_tweets_service_tweets_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllTweetsResponse) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

type GetTweetsOfUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetTweetsOfUserRequest) Reset() {
	*x = GetTweetsOfUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTweetsOfUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetsOfUserRequest) ProtoMessage() {}

func (x *GetTweetsOfUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetsOfUserRequest.ProtoReflect.Descriptor instead.
func (*GetTweetsOfUserRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_tweets_service_tweets_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetTweetsOfUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTweetsOfUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tweets []*Tweet `protobuf:"bytes,1,rep,name=tweets,proto3" json:"tweets,omitempty"`
}

func (x *GetTweetsOfUserResponse) Reset() {
	*x = GetTweetsOfUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTweetsOfUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetsOfUserResponse) ProtoMessage() {}

func (x *GetTweetsOfUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_tweets_service_tweets_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetsOfUserResponse.ProtoReflect.Descriptor instead.
func (*GetTweetsOfUserResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_tweets_service_tweets_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetTweetsOfUserResponse) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

var File_protobuf_tweets_service_tweets_service_proto protoreflect.FileDescriptor

var file_protobuf_tweets_service_tweets_service_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x77, 0x65, 0x65, 0x74,
	0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x74, 0x77, 0x65, 0x65, 0x74, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb9, 0x01, 0x0a, 0x05, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65,
	0x73, 0x5f, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x70, 0x6c,
	0x69, 0x65, 0x73, 0x54, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x5f, 0x74,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x54, 0x6f,
	0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x79, 0x0a, 0x10, 0x50,
	0x6f, 0x73, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x5f, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x54, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x71,
	0x75, 0x6f, 0x74, 0x65, 0x5f, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71,
	0x75, 0x6f, 0x74, 0x65, 0x54, 0x6f, 0x22, 0x31, 0x0a, 0x11, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x77,
	0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x74,
	0x77, 0x65, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x77, 0x65,
	0x65, 0x74, 0x52, 0x05, 0x74, 0x77, 0x65, 0x65, 0x74, 0x22, 0x33, 0x0a, 0x16, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x77, 0x65, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x77, 0x65, 0x65, 0x74, 0x49, 0x64, 0x22, 0x19,
	0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x77, 0x65, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x77, 0x65, 0x65, 0x74, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x74, 0x77, 0x65, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x05, 0x74, 0x77, 0x65, 0x65,
	0x74, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x54, 0x77, 0x65, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1e, 0x0a, 0x06, 0x74, 0x77, 0x65, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x06, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x06, 0x74, 0x77, 0x65, 0x65, 0x74, 0x73,
	0x22, 0x31, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x73, 0x4f, 0x66, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x73,
	0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x06, 0x74, 0x77, 0x65, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06,
	0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x06, 0x74, 0x77, 0x65, 0x65, 0x74, 0x73, 0x32, 0xc3,
	0x02, 0x0a, 0x0d, 0x54, 0x77, 0x65, 0x65, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x32, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x11, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x77,
	0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x54, 0x77, 0x65, 0x65, 0x74, 0x73, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x54, 0x77, 0x65, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x77, 0x65, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x73, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x77, 0x65,
	0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x74, 0x77, 0x65, 0x65, 0x74, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_tweets_service_tweets_service_proto_rawDescOnce sync.Once
	file_protobuf_tweets_service_tweets_service_proto_rawDescData = file_protobuf_tweets_service_tweets_service_proto_rawDesc
)

func file_protobuf_tweets_service_tweets_service_proto_rawDescGZIP() []byte {
	file_protobuf_tweets_service_tweets_service_proto_rawDescOnce.Do(func() {
		file_protobuf_tweets_service_tweets_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_tweets_service_tweets_service_proto_rawDescData)
	})
	return file_protobuf_tweets_service_tweets_service_proto_rawDescData
}

var file_protobuf_tweets_service_tweets_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protobuf_tweets_service_tweets_service_proto_goTypes = []interface{}{
	(*Tweet)(nil),                   // 0: Tweet
	(*PostTweetRequest)(nil),        // 1: PostTweetRequest
	(*PostTweetResponse)(nil),       // 2: PostTweetResponse
	(*DeleteTweetByIdRequest)(nil),  // 3: DeleteTweetByIdRequest
	(*DeleteTweetByIdResponse)(nil), // 4: DeleteTweetByIdResponse
	(*GetTweetByIdRequest)(nil),     // 5: GetTweetByIdRequest
	(*GetTweetByIdResponse)(nil),    // 6: GetTweetByIdResponse
	(*GetAllTweetsRequest)(nil),     // 7: GetAllTweetsRequest
	(*GetAllTweetsResponse)(nil),    // 8: GetAllTweetsResponse
	(*GetTweetsOfUserRequest)(nil),  // 9: GetTweetsOfUserRequest
	(*GetTweetsOfUserResponse)(nil), // 10: GetTweetsOfUserResponse
	(*timestamp.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_protobuf_tweets_service_tweets_service_proto_depIdxs = []int32{
	11, // 0: Tweet.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: PostTweetResponse.tweet:type_name -> Tweet
	0,  // 2: GetTweetByIdResponse.tweet:type_name -> Tweet
	0,  // 3: GetAllTweetsResponse.tweets:type_name -> Tweet
	0,  // 4: GetTweetsOfUserResponse.tweets:type_name -> Tweet
	1,  // 5: TweetsService.PostTweet:input_type -> PostTweetRequest
	3,  // 6: TweetsService.DeleteTweetById:input_type -> DeleteTweetByIdRequest
	5,  // 7: TweetsService.GetTweetById:input_type -> GetTweetByIdRequest
	7,  // 8: TweetsService.GetAllTweets:input_type -> GetAllTweetsRequest
	5,  // 9: TweetsService.GetTweetsOfUser:input_type -> GetTweetByIdRequest
	2,  // 10: TweetsService.PostTweet:output_type -> PostTweetResponse
	4,  // 11: TweetsService.DeleteTweetById:output_type -> DeleteTweetByIdResponse
	6,  // 12: TweetsService.GetTweetById:output_type -> GetTweetByIdResponse
	8,  // 13: TweetsService.GetAllTweets:output_type -> GetAllTweetsResponse
	6,  // 14: TweetsService.GetTweetsOfUser:output_type -> GetTweetByIdResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protobuf_tweets_service_tweets_service_proto_init() }
func file_protobuf_tweets_service_tweets_service_proto_init() {
	if File_protobuf_tweets_service_tweets_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_tweets_service_tweets_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tweet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_tweets_service_tweets_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostTweetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_tweets_service_tweets_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostTweetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_tweets_service_tweets_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTweetByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_tweets_service_tweets_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTweetByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_tweets_service_tweets_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTweetByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_tweets_service_tweets_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTweetByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_tweets_service_tweets_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllTweetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_tweets_service_tweets_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllTweetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_tweets_service_tweets_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTweetsOfUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_tweets_service_tweets_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTweetsOfUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_tweets_service_tweets_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_tweets_service_tweets_service_proto_goTypes,
		DependencyIndexes: file_protobuf_tweets_service_tweets_service_proto_depIdxs,
		MessageInfos:      file_protobuf_tweets_service_tweets_service_proto_msgTypes,
	}.Build()
	File_protobuf_tweets_service_tweets_service_proto = out.File
	file_protobuf_tweets_service_tweets_service_proto_rawDesc = nil
	file_protobuf_tweets_service_tweets_service_proto_goTypes = nil
	file_protobuf_tweets_service_tweets_service_proto_depIdxs = nil
}
